---
- name: Install Python3, pip3, boto3, jq, and AWS CLI
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - jq
    - awscli

- name: Install boto3 using pip3
  become: true
  pip:
    name: boto3
    state: present
